#! /bin/sh
export SCONS_REL=20-09-10
export SCONS_VARIANT=redhat6-x86_64-64bit-gcc44
export SCONS_VERSION=Optimized
export SCONS_TOTAL=${SCONS_VARIANT}-${SCONS_VERSION}
export SCONS_BUILDS=/sdf/group/fermi/n/u52/ReleaseManagerBuild/
export GLAST_EXT_BASE=/sdf/group/fermi/a/ground/GLAST_EXT
export GLAST_EXT=${GLAST_EXT_BASE}/${SCONS_VARIANT}
export PARENT=${SCONS_BUILDS}/${SCONS_VARIANT}/${SCONS_VERSION}/GlastRelease/${SCONS_REL}
export RELEASE=/sdf/home/a/abhishek/ACD_calib/release/GR-${SCONS_REL}
export INST_DIR=$RELEASE
export BASE_DIR=$PARENT
export CALIBGENACDROOT=$RELEASE/calibGenACD/
export FACILITIESROOT=$PARENT/facilities
export RDBMODELROOT=$PARENT/rdbmodel
#unset PYTHONPATH
#unset LD_LIBRARY_PATH
#unset DYLD_LIBRARY_PATH