#!/bin/sh                                                                                                
/sdf/group/fermi/ground/trendableData/bin/trendableData org.glast.trendabledata.fill.AddMetaDataToDataEntry $*
# rest of your script