#!/bin/sh                                                                                                
/sdf/group/fermi/ground/trendableData/bin/trendableData org.glast.trendabledata.fill.AddDataToDataEntry $*
# rest of your script
